'use strict';
// Printable HTML report (Print → PDF) + SARIF 2.1.0 export for CI / code-scanning. Pure: a scan
// record in, a string / JSON object out.
const esc = (s) => String(s == null ? '' : s).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
const SEV_ORDER = { crit: 0, high: 1, med: 2, low: 3, info: 4 };

function securityReportHtml(record) {
  if (!record || record.scanned === false) return `<!doctype html><meta charset="utf-8"><title>Security report</title><body style="font-family:system-ui;padding:40px">No scan on record for this project. Run a scan first.</body>`;
  const g = record.grade || {}, c = g.counts || {};
  const rows = (record.findings || []).slice().sort((a, b) => ({ fail: 0, warn: 1, ok: 2, na: 3 }[a.status] - { fail: 0, warn: 1, ok: 2, na: 3 }[b.status]) || (SEV_ORDER[a.severity] - SEV_ORDER[b.severity]));
  const statusLabel = { ok: 'PASS', fail: 'FAIL', warn: 'REVIEW', na: 'N/A' };
  const comp = record.compliance || {};
  const compHtml = Object.values(comp).map((s) => `<li><b>${esc(s.label)}</b>: ${s.pass}/${s.total} categories passing <span class="muted">(${s.categories.map((k) => `${k.owasp}:${statusLabel[k.status]}`).join(', ')})</span></li>`).join('');
  const findingHtml = rows.map((f) => `
    <section class="f ${f.status}">
      <h3>${esc(f.title)} <span class="tag">${esc(f.owasp)}</span> <span class="chip ${f.status}">${statusLabel[f.status] || f.status}</span> <span class="sev">${esc(f.severity)}</span></h3>
      <div class="meta">${esc(f.category)} · ${esc(f.kind)} · ${esc(f.standard)}</div>
      ${f.scenario ? `<p class="scen"><b>Attack scenario:</b> ${esc(f.scenario)}</p>` : ''}
      ${f.evidence ? `<pre class="ev">${esc(f.evidence)}</pre>` : ''}
      ${f.fix ? `<pre class="fix"><b>Remediation</b>\n${esc(f.fix)}</pre>` : ''}
    </section>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>Security report — ${esc(record.name)}</title>
<style>
  :root{--fail:#b91c1c;--warn:#b45309;--ok:#15803d;--na:#64748b}
  *{box-sizing:border-box} body{font-family:ui-sans-serif,system-ui,-apple-system;color:#0f172a;margin:0;padding:40px;max-width:900px;margin:auto}
  header{border-bottom:2px solid #0f172a;padding-bottom:16px;margin-bottom:24px}
  h1{margin:0 0 4px;font-size:24px} .muted{color:#64748b;font-weight:400}
  .grade{font-size:40px;font-weight:800;float:right;line-height:1}
  .summary{display:flex;gap:16px;margin:12px 0}
  .summary div{background:#f1f5f9;border-radius:8px;padding:8px 14px;font-size:14px}
  ul{padding-left:18px} li{margin:4px 0;font-size:14px}
  .f{border:1px solid #e2e8f0;border-left-width:4px;border-radius:8px;padding:12px 16px;margin:12px 0;page-break-inside:avoid}
  .f.fail{border-left-color:var(--fail)} .f.warn{border-left-color:var(--warn)} .f.ok{border-left-color:var(--ok)} .f.na{border-left-color:var(--na)}
  h3{margin:0 0 4px;font-size:16px} .meta{color:#64748b;font-size:12px;margin-bottom:6px}
  .tag{background:#0f172a;color:#fff;font-size:11px;padding:1px 6px;border-radius:4px;vertical-align:middle}
  .chip{font-size:11px;padding:1px 6px;border-radius:4px;color:#fff} .chip.fail{background:var(--fail)} .chip.warn{background:var(--warn)} .chip.ok{background:var(--ok)} .chip.na{background:var(--na)}
  .sev{font-size:11px;color:#64748b;text-transform:uppercase}
  .scen{font-size:13px;background:#fff7ed;padding:8px 10px;border-radius:6px}
  pre{white-space:pre-wrap;word-break:break-word;font-size:12px;background:#f8fafc;border-radius:6px;padding:10px;overflow:auto}
  pre.fix{background:#f0fdf4}
  @media print{body{padding:0} .f{break-inside:avoid}}
</style></head><body>
<header>
  <div class="grade">${esc(g.letter || '—')}</div>
  <h1>Security assessment — ${esc(record.name)}</h1>
  <div class="muted">${esc(record.type || '')} · scanned ${esc((record.scannedAt || '').slice(0, 16).replace('T', ' '))}</div>
  <div class="summary">
    <div><b>${g.score != null ? g.score : '—'}</b>/100</div>
    <div style="color:var(--fail)"><b>${c.fail || 0}</b> failing</div>
    <div style="color:var(--warn)"><b>${c.warn || 0}</b> review</div>
    <div style="color:var(--ok)"><b>${c.ok || 0}</b> pass</div>
  </div>
  ${compHtml ? `<b>OWASP coverage</b><ul>${compHtml}</ul>` : ''}
</header>
${findingHtml}
<footer class="muted" style="margin-top:24px;font-size:12px">Generated by Mobile DevTools · Mobile Security. All checks are static and read-only.</footer>
</body></html>`;
}

// CWE mapping (per-check, then per-OWASP fallback) for SARIF rule metadata.
const CWE = { 'hardcoded-secrets': 798, 'committed-secrets': 798, 'google-api-key-restriction': 798, 'plaintext-token': 312, 'allow-backup': 312, 'cleartext-traffic': 319, 'ios-ats': 319, 'cert-pinning': 295, 'network-security-config': 319, 'insecure-tls-override': 295, 'weak-crypto': 327, 'insecure-random': 338, 'secrets-in-logs': 532, 'clipboard-sensitive': 200, 'webview-misconfig': 749, 'exported-components': 926, 'deep-link-hijack': 939, 'sql-injection-local': 89, 'weak-biometric': 287, 'root-jailbreak': 693, 'anti-debug': 489, 'obfuscation': 656, 'debug-signing': 347, 'release-debuggable': 489, 'flag-secure': 200, 'tapjacking': 1021, 'keyboard-cache': 524, 'dangerous-permissions': 250, 'replay-masking': 359, 'outdated-deps-mobile': 1104 };
const CWE_BY_OWASP = { M1: 798, M2: 1104, M3: 287, M4: 20, M5: 319, M6: 359, M7: 693, M8: 16, M9: 312, M10: 327 };
const cweOf = (f) => CWE[f.id] || CWE_BY_OWASP[f.owasp] || null;
const SARIF_LEVEL = (f) => f.status === 'fail' ? ((f.severity === 'crit' || f.severity === 'high') ? 'error' : (f.severity === 'low' || f.severity === 'info') ? 'note' : 'warning') : 'note';

function securitySarif(record) {
  const findings = ((record && record.findings) || []).filter((f) => f.status === 'fail' || f.status === 'warn');
  const rulesById = {};
  for (const f of findings) if (!rulesById[f.id]) { const cwe = cweOf(f); rulesById[f.id] = { id: f.id, name: f.title, shortDescription: { text: f.title }, properties: { category: f.category, owasp: f.owasp || '', cwe: cwe ? 'CWE-' + cwe : '', tags: ['security', ...(cwe ? ['external/cwe/cwe-' + cwe] : [])], 'security-severity': ({ crit: '9.5', high: '8.0', med: '5.5', low: '3.0', info: '1.0' }[f.severity] || '1.0') } }; }
  const results = findings.map((f) => {
    const res = { ruleId: f.id, level: SARIF_LEVEL(f), message: { text: `${f.title}${f.evidence ? '\n' + f.evidence : ''}`.slice(0, 2000) } };
    const m = (f.evidence || '').match(/([\w./-]+):(\d+)/);   // best-effort file:line from evidence
    if (m) res.locations = [{ physicalLocation: { artifactLocation: { uri: m[1] }, region: { startLine: +m[2] } } }];
    return res;
  });
  return { version: '2.1.0', $schema: 'https://json.schemastore.org/sarif-2.1.0.json', runs: [{ tool: { driver: { name: 'mobile-security', informationUri: 'https://github.com/', rules: Object.values(rulesById) } }, results }] };
}

module.exports = { securityReportHtml, securitySarif };
