'use strict';
// Printable / CI report renderers — a standalone HTML QA report, a JUnit XML export (one testcase
// per check), and a per-file coverage table from lcov. Pure string builders (coverageHtml reads lcov).
const fs = require('fs');
const path = require('path');
const esc = (s) => String(s == null ? '' : s).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));

function qaReportHtml(record) {
  if (!record || record.ran === false) return `<!doctype html><meta charset="utf-8"><body style="font-family:system-ui;padding:40px">No QA run on record. Run QA first.</body>`;
  const g = record.grade || {}, c = g.counts || {};
  const label = { pass: 'PASS', ok: 'PASS', fail: 'FAIL', warn: 'REVIEW', na: 'N/A' };
  const rows = (record.results || []).slice().sort((a, b) => ({ fail: 0, warn: 1, ok: 2, pass: 2, na: 3 }[a.status] - { fail: 0, warn: 1, ok: 2, pass: 2, na: 3 }[b.status]));
  const sumHtml = Object.entries(record.summary || {}).map(([cat, s]) => `<li><b>${esc(cat)}</b>: ${label[s.status]}${s.metric ? ' (' + esc(s.metric) + ')' : ''}</li>`).join('');
  const body = rows.map((f) => `<section class="f ${f.status}"><h3>${esc(f.title)} <span class="chip ${f.status}">${label[f.status] || f.status}</span>${f.metric ? ` <span class="m">${esc(f.metric)}</span>` : ''}</h3><div class="meta">${esc(f.category)} · ${esc(f.kind)}</div>${f.detail ? `<pre>${esc(f.detail)}</pre>` : ''}${f.fix ? `<pre class="fix"><b>How to improve</b>\n${esc(f.fix)}</pre>` : ''}</section>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>QA report — ${esc(record.name)}</title><style>
    :root{--fail:#b91c1c;--warn:#b45309;--ok:#15803d;--na:#64748b}*{box-sizing:border-box}body{font-family:ui-sans-serif,system-ui;color:#0f172a;max-width:900px;margin:auto;padding:40px}
    header{border-bottom:2px solid #0f172a;padding-bottom:16px;margin-bottom:24px}h1{margin:0 0 4px;font-size:24px}.muted{color:#64748b}.grade{font-size:40px;font-weight:800;float:right}
    .summary{display:flex;gap:14px;margin:12px 0}.summary div{background:#f1f5f9;border-radius:8px;padding:8px 14px;font-size:14px}
    ul{padding-left:18px}li{font-size:14px;margin:3px 0}.f{border:1px solid #e2e8f0;border-left-width:4px;border-radius:8px;padding:12px 16px;margin:12px 0;page-break-inside:avoid}
    .f.fail{border-left-color:var(--fail)}.f.warn{border-left-color:var(--warn)}.f.pass,.f.ok{border-left-color:var(--ok)}.f.na{border-left-color:var(--na)}
    h3{margin:0 0 4px;font-size:16px}.meta{color:#64748b;font-size:12px;margin-bottom:6px}.m{font-size:12px;color:#334155;background:#eef2ff;padding:1px 6px;border-radius:4px}
    .chip{font-size:11px;padding:1px 6px;border-radius:4px;color:#fff}.chip.fail{background:var(--fail)}.chip.warn{background:var(--warn)}.chip.pass,.chip.ok{background:var(--ok)}.chip.na{background:var(--na)}
    pre{white-space:pre-wrap;font-size:12px;background:#f8fafc;border-radius:6px;padding:10px}pre.fix{background:#f0fdf4}@media print{body{padding:0}}
  </style></head><body><header><div class="grade">${esc(g.letter || '—')}</div><h1>QA report — ${esc(record.name)}</h1>
  <div class="muted">${esc(record.type || '')} · ran ${esc((record.ranAt || '').slice(0, 16).replace('T', ' '))}</div>
  <div class="summary"><div><b>${g.score != null ? g.score : '—'}</b>/100</div><div style="color:var(--fail)"><b>${c.fail || 0}</b> failing</div><div style="color:var(--warn)"><b>${c.warn || 0}</b> review</div><div style="color:var(--ok)"><b>${c.pass || 0}</b> pass</div></div>
  ${sumHtml ? `<b>Quality summary</b><ul>${sumHtml}</ul>` : ''}</header>${body}
  <footer class="muted" style="margin-top:24px;font-size:12px">Generated by Mobile DevTools — Mobile QA.</footer></body></html>`;
}
// JUnit XML (one testcase per check) for CI dashboards.
function junitXml(rec) {
  const e = (s) => String(s == null ? '' : s).replace(/[<&>"]/g, (c) => ({ '<': '&lt;', '&': '&amp;', '>': '&gt;', '"': '&quot;' }[c]));
  const results = rec.results || [];
  const cases = results.map((f) => {
    const inner = f.status === 'fail' ? `<failure message="${e(f.metric || 'failed')}">${e(f.detail || '')}</failure>` : f.status === 'na' ? '<skipped/>' : '';
    return `  <testcase classname="${e(rec.name)}.${e(f.category)}" name="${e(f.title)}">${inner}</testcase>`;
  }).join('\n');
  const fails = results.filter((f) => f.status === 'fail').length, skips = results.filter((f) => f.status === 'na').length;
  return `<?xml version="1.0" encoding="UTF-8"?>\n<testsuites>\n <testsuite name="${e(rec.name)}" tests="${results.length}" failures="${fails}" skipped="${skips}">\n${cases}\n </testsuite>\n</testsuites>\n`;
}
// Per-file coverage table from coverage/lcov.info.
function coverageHtml(projectPath) {
  const lcov = path.join(projectPath || '', 'coverage', 'lcov.info');
  if (!projectPath || !fs.existsSync(lcov)) return `<!doctype html><meta charset="utf-8"><body style="font-family:system-ui;padding:40px">No coverage/lcov.info — run <code>flutter test --coverage</code> first.</body>`;
  const files = []; let cur = null;
  for (const l of fs.readFileSync(lcov, 'utf8').split('\n')) {
    if (l.startsWith('SF:')) cur = { file: l.slice(3), lf: 0, lh: 0 };
    else if (l.startsWith('LF:')) cur && (cur.lf += +l.slice(3) || 0);
    else if (l.startsWith('LH:')) cur && (cur.lh += +l.slice(3) || 0);
    else if (l.startsWith('end_of_record') && cur) { cur.pct = cur.lf ? Math.round(100 * cur.lh / cur.lf) : 0; files.push(cur); cur = null; }
  }
  files.sort((a, b) => a.pct - b.pct);
  const tf = files.reduce((s, f) => s + f.lf, 0), th = files.reduce((s, f) => s + f.lh, 0), tot = tf ? Math.round(100 * th / tf) : 0;
  const rows = files.map((f) => { const col = f.pct >= 80 ? '#15803d' : f.pct >= 50 ? '#b45309' : '#b91c1c'; return `<tr><td style="font-family:ui-monospace,monospace;font-size:12px">${esc(f.file.replace(projectPath + '/', ''))}</td><td style="text-align:right;color:${col};font-weight:600">${f.pct}%</td><td style="text-align:right;color:#64748b">${f.lh}/${f.lf}</td></tr>`; }).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>Coverage — ${esc(path.basename(projectPath))}</title><style>body{font-family:ui-sans-serif,system-ui;max-width:900px;margin:auto;padding:40px;color:#0f172a}h1{font-size:22px}table{width:100%;border-collapse:collapse}td,th{padding:6px 10px;border-bottom:1px solid #e2e8f0}th{text-align:left;font-size:12px;color:#64748b}</style></head><body><h1>Coverage — ${esc(path.basename(projectPath))} · ${tot}%</h1><div style="color:#64748b;margin-bottom:12px">${th}/${tf} lines · ${files.length} files (lowest first)</div><table><thead><tr><th>File</th><th style="text-align:right">Coverage</th><th style="text-align:right">Lines</th></tr></thead><tbody>${rows}</tbody></table></body></html>`;
}
module.exports = { qaReportHtml, junitXml, coverageHtml };
