'use strict';
// Named preset stacks. Each is a partial merged over defaultConfig by the UI / api
// before generation.

const RECIPES = [
  {
    id: 'structured-getx-standard',
    label: 'Structured · GetX (standard)',
    description: 'Structured GetX house stack: GetX, general_exports barrel, ApiRequest, get_storage, smart_dialog.',
    config: {
      mode: 'structured-getx',
      stateMgmt: 'getx',
      architecture: 'feature-folder',
      navigation: 'named-routes',
      apiClient: 'api_request',
      localization: 'intl',
      themes: ['light', 'dark'],
      connectivity: ['connectivity_plus'],
      components: ['cached_network_image', 'flutter_svg', 'flutter_smart_dialog'],
      logging: ['consoleLog'],
      assets: ['launcher_icons', 'native_splash'],
      testing: true,
      features: ['splash', 'auth', 'home'],
    },
  },
  {
    id: 'structured-riverpod-standard',
    label: 'Structured · Riverpod (standard)',
    description: 'Structured Riverpod house stack: raw flutter_riverpod, GoRouter + globalArguments, shared_preferences, flutter_localization.',
    config: {
      mode: 'structured-riverpod',
      stateMgmt: 'riverpod',
      architecture: 'feature-folder',
      navigation: 'go_router',
      apiClient: 'api_request',
      localization: 'flutter_localization',
      themes: ['light', 'dark'],
      connectivity: ['connectivity_plus'],
      components: ['cached_network_image', 'flutter_svg', 'flutter_smart_dialog'],
      logging: ['consoleLog'],
      assets: ['launcher_icons', 'native_splash'],
      testing: true,
      features: ['splash', 'auth', 'home'],
    },
  },
  {
    id: 'minimal',
    label: 'Minimal',
    description: 'Vanilla Flutter, layer folders, no state library — a clean starting point.',
    config: {
      mode: 'generic',
      stateMgmt: 'none',
      architecture: 'layer-folder',
      navigation: 'go_router',
      apiClient: 'http',
      localization: 'none',
      themes: ['light'],
      interactivity: [],
      connectivity: [],
      components: [],
      logging: [],
      assets: [],
      testing: false,
      features: ['home'],
    },
  },
  {
    id: 'enterprise',
    label: 'Enterprise',
    description: 'Structured Riverpod with the full observability + delivery stack (Firebase, push, remote config, flavors).',
    config: {
      mode: 'structured-riverpod',
      stateMgmt: 'riverpod',
      architecture: 'feature-folder',
      navigation: 'go_router',
      apiClient: 'api_request',
      localization: 'flutter_localization',
      themes: ['light', 'dark', 'dynamic'],
      connectivity: ['connectivity_plus', 'internet_connection_checker_plus'],
      firebase: ['core', 'analytics', 'crashlytics', 'performance', 'remote_config'],
      notifications: ['local', 'push'],
      security: ['secure_storage', 'recaptcha'],
      components: ['cached_network_image', 'flutter_svg', 'flutter_smart_dialog'],
      logging: ['consoleLog', 'pretty_dio_logger'],
      permissions: ['notifications', 'camera'],
      assets: ['launcher_icons', 'native_splash', 'svg'],
      testing: true,
      flavors: ['dev', 'staging', 'prod'],
      features: ['splash', 'auth', 'home', 'profile'],
    },
  },
];

module.exports = { RECIPES };
